### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by LordKlaus** [siunus/duco-monitor#1]
https://siunus.github.io/duco-monitor is no longer getting data properly, do not show online workers, the estimated profit, the balance.

**Comment by siunus** [comment]
@LordKlaus it's because the API provided by duinocoin has changed. I have updated. You can try again.

**Comment by siunus** [comment]
Just trying Comments Widget by [utteranc.es](https://utteranc.es/)

**Comment by jeffsandy22** [comment]
That's cool.
