### ISSUE TITLE
i love it.... BUT... lol

### ISSUE THREAD

**Issue by DrBlackross** [siunus/duco-monitor#7]
is there a way to adjust the time marks on the bottom of the graph? im trying to see when the system battery dies LOL

or let alone port it to the esp32 webserver

**Comment by siunus** [comment]
Unfortunately, there is currently no built-in way to adjust the time marks on the bottom of the graph.

**Comment by DrBlackross** [comment]
k thanks, i think the hardest part of duinocoin is getting verified lol
