### ISSUE TITLE
Toggle the dude off

### ISSUE THREAD

**Issue by tgwaste** [siunus/duco-monitor#8]
Would be great for a toggle to get rid of the dude on his laptop, especially for mobile. It takes a lot of space where it's better to see information instead of a picture.

**Comment by siunus** [comment]
Updated
https://github.com/siunus/duco-monitor/commit/6fc93c7746425714013bd8b4097f54716db78fe8

**Comment by tgwaste** [comment]
Great, now have miners and hashrate be above mined coins and you got a winner.
